# Generated by Django 5.1.6 on 2025-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Ana Yemek'), ('soup', 'Corba'), ('dessert', 'Tatlı'), ('salad', 'Salata'), ('other', 'Diğer')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
